window.DATA = [
  {
    "row": 2,
    "caso": "1",
    "casoRaiz": "1",
    "id": "001/2026",
    "semId": false,
    "etapa": "Diligência",
    "origem": "Monitoramento 2026",
    "clube": "SAF Botafogo",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Acompanhar envio de documentos",
    "dataEnvio": "13/03/2026",
    "prazoFinal": "13/04/2026",
    "dataEntrega": "",
    "observacao": "Documentos não entregues na Diligência, apenas entregue após o PSS",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "https://drive.google.com/file/d/1KnUvIZmQIlRH2k2h1KjzCAyXwP7ZOtpn/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 3,
    "caso": "1",
    "casoRaiz": "1",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "Monitoramento 2026",
    "clube": "SAF Botafogo",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Aguardando documentação solicitado no Acórdão",
    "dataEnvio": "03/06/2026",
    "prazoFinal": "18/06/2026",
    "dataEntrega": "18/06/2026",
    "observacao": "Documentos entregues",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 4,
    "caso": "1",
    "casoRaiz": "1",
    "id": "",
    "semId": true,
    "etapa": "Parecer Técnico",
    "origem": "Monitoramento 2026",
    "clube": "SAF Botafogo",
    "serie": "A",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "Para possível abertura de Processo Sancionador",
    "dataEnvio": "18/06/2026",
    "prazoFinal": "10/07/2026",
    "dataEntrega": "",
    "observacao": "Aguardando Análise Técnica",
    "statusEtapa": "Pendente ANRESF",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 5,
    "caso": "1.1",
    "casoRaiz": "1",
    "id": "001/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "Monitoramento 2026",
    "clube": "SAF Botafogo",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Pelo não envio de documentação",
    "dataEnvio": "15/04/2026",
    "prazoFinal": "20/04/2026",
    "dataEntrega": "20/04/2026",
    "observacao": "Defesa apresentada e documentos entregues com marca d'água",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Multa 100k + 20k por dia",
    "doc": "https://drive.google.com/file/d/1W5wD-y8uPUhkE_AflCzaSwXXJJODK3nS/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 6,
    "caso": "1.1",
    "casoRaiz": "1",
    "id": "001/2026",
    "semId": false,
    "etapa": "Acórdão - PSS",
    "origem": "Monitoramento 2026",
    "clube": "SAF Botafogo",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Turma de Julgamento 02",
    "dataEnvio": "03/06/2026",
    "prazoFinal": "18/06/2026",
    "dataEntrega": "",
    "observacao": "Turma 02 - Decidido que documentos enviados não eram válidos + Novo Prazo para envio da documentação",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1dAMoj1fVpJNiJHgE_uq8B1LL-yk9jmCC/view?usp=drive_link",
    "turma": "Turma 02",
    "dataDecisao": "29/05/2026",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 7,
    "caso": "1.1",
    "casoRaiz": "1",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "Monitoramento 2026",
    "clube": "SAF Botafogo",
    "serie": "A",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "5 dias úties para reconsideração",
    "dataEnvio": "03/06/2026",
    "prazoFinal": "11/06/2026",
    "dataEntrega": "",
    "observacao": "Não houve pedido de reconsideração",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 8,
    "caso": "2",
    "casoRaiz": "2",
    "id": "002/2026",
    "semId": false,
    "etapa": "Diligência",
    "origem": "Monitoramento 2026",
    "clube": "Ponte Preta",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Acompanhar envio de documentos",
    "dataEnvio": "09/04/2026",
    "prazoFinal": "05/05/2026",
    "dataEntrega": "",
    "observacao": "Aguardando documentação para Análise Técnica",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "",
    "doc": "https://drive.google.com/file/d/1pC9gQxxQBy1VGoPUBeFIDRuXhJMK2X-A/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 9,
    "caso": "2",
    "casoRaiz": "2",
    "id": "",
    "semId": true,
    "etapa": "Parecer Técnico",
    "origem": "Monitoramento 2026",
    "clube": "Ponte Preta",
    "serie": "B",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Para possível abertura de Processo Sancionador",
    "dataEnvio": "13/05/2026",
    "prazoFinal": "22/05/2026",
    "dataEntrega": "",
    "observacao": "Abertura aprovada pela Presidência da ANRESF",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 10,
    "caso": "2",
    "casoRaiz": "2",
    "id": "017/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Monitoramento 2026",
    "clube": "Ponte Preta",
    "serie": "B",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "Descumprimento do Requisito de Solvência",
    "dataEnvio": "22/05/2026",
    "prazoFinal": "08/06/2026",
    "dataEntrega": "01/06/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência + Exclusão PARF-B",
    "doc": "https://drive.google.com/file/d/1LrBLAacEEwfFU-8jHiYyD2FDnqPZ7M7P/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 11,
    "caso": "2",
    "casoRaiz": "2",
    "id": "002/2026",
    "semId": false,
    "etapa": "Parecer Técnico Conclusivo",
    "origem": "Monitoramento 2026",
    "clube": "Ponte Preta",
    "serie": "B",
    "ordem": 4,
    "ordemLabel": "4",
    "objeto": "Para distribuição das Turmas de Julgamento",
    "dataEnvio": "08/06/2026",
    "prazoFinal": "15/06/2026",
    "dataEntrega": "12/06/2026",
    "observacao": "Documentação enviada para avaliação da Turma 02",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "",
    "doc": "https://drive.google.com/file/d/16kopd6IN-ah7qOrCDyi3GLjHfOnkPg1W/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 12,
    "caso": "2",
    "casoRaiz": "2",
    "id": "017/2026",
    "semId": false,
    "etapa": "Acórdão - PSO",
    "origem": "Monitoramento 2026",
    "clube": "Ponte Preta",
    "serie": "B",
    "ordem": 5,
    "ordemLabel": "5",
    "objeto": "Avaliação pela Turma de Julgamento 02",
    "dataEnvio": "15/06/2026",
    "prazoFinal": "15/06/2026",
    "dataEntrega": "",
    "observacao": "Turma 02 - Decidido advertência + Exclusão do PARF-B",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência + Exclusão PARF-B",
    "doc": "https://drive.google.com/file/d/155rp4T5GKQ3O_SZdQxd95vo9OeFsnLWO/view?usp=drive_link",
    "turma": "Turma 02",
    "dataDecisao": "15/06/2026",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 13,
    "caso": "2",
    "casoRaiz": "2",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "Monitoramento 2026",
    "clube": "Ponte Preta",
    "serie": "B",
    "ordem": 6,
    "ordemLabel": "6",
    "objeto": "Acompanhar possível Recurso sobre o PSO 017/2026",
    "dataEnvio": "15/06/2026",
    "prazoFinal": "29/06/2026",
    "dataEntrega": "",
    "observacao": "Não houve pedido de Recurso",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 14,
    "caso": "2.1",
    "casoRaiz": "2",
    "id": "002/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "Monitoramento 2026",
    "clube": "Ponte Preta",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Pelo não envio de documentação",
    "dataEnvio": "08/05/2026",
    "prazoFinal": "13/05/2026",
    "dataEntrega": "13/05/2026",
    "observacao": "Defesa apresentada e documentos entregues",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência + Multa 50k + 10k por dia",
    "doc": "https://drive.google.com/file/d/1NorTIiQ38z0uCf4teCHHVSmQifxwfnxB/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 15,
    "caso": "2.1",
    "casoRaiz": "2",
    "id": "002/2026",
    "semId": false,
    "etapa": "Acórdão - PSS",
    "origem": "Monitoramento 2026",
    "clube": "Ponte Preta",
    "serie": "B",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Turma de Julgamento 01",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "05/06/2026",
    "dataEntrega": "",
    "observacao": "Turma 01 - Decidido advertência por não envio de documentação",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1ttRWbpBLSI-EolnA8rR1l4LYZCrW65vF/view?usp=drive_link",
    "turma": "Turma 01",
    "dataDecisao": "29/05/2026",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 16,
    "caso": "2.1",
    "casoRaiz": "2",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "Monitoramento 2026",
    "clube": "Ponte Preta",
    "serie": "B",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "5 dias úties para reconsideração",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "12/06/2026",
    "dataEntrega": "",
    "observacao": "Não houve pedido de reconsideração",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 17,
    "caso": "3",
    "casoRaiz": "3",
    "id": "003/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "DF 2026",
    "clube": "Fluminense",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do dever de publicação das DFs",
    "dataEnvio": "15/05/2026",
    "prazoFinal": "20/05/2026",
    "dataEntrega": "",
    "observacao": "O Clube não apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência + Multa 40k",
    "doc": "https://drive.google.com/file/d/1qRDEnC4q3JFZqY7mmSauQ62Q51aqI92/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 18,
    "caso": "3",
    "casoRaiz": "3",
    "id": "003/2026",
    "semId": false,
    "etapa": "Acórdão - PSS",
    "origem": "DF 2026",
    "clube": "Fluminense",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Turma de Julgamento 01",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "05/06/2026",
    "dataEntrega": "",
    "observacao": "Turma 01 - Decidido advertência por não publicação das DFs + Prazo para publicação",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/19aGF21fsHbRggnklupuilP0nge1wAAl9/view?usp=drive_link",
    "turma": "Turma 01",
    "dataDecisao": "29/05/2026",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 19,
    "caso": "3",
    "casoRaiz": "3",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "Fluminense",
    "serie": "A",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "5 dias úties para reconsideração",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "12/06/2026",
    "dataEntrega": "",
    "observacao": "Não houve pedido de reconsideração",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 20,
    "caso": "3.1",
    "casoRaiz": "3",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "Fluminense",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Acompanhar publicação das DFs",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "26/06/2026",
    "dataEntrega": "",
    "observacao": "Acompanhar publicação das DFs",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 21,
    "caso": "4",
    "casoRaiz": "4",
    "id": "004/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "DF 2026",
    "clube": "Palmeiras",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do dever de publicação das DFs",
    "dataEnvio": "15/05/2026",
    "prazoFinal": "20/05/2026",
    "dataEntrega": "20/05/2026",
    "observacao": "O Clube apresentou defesa e DF publicada",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência + Multa 40k",
    "doc": "https://drive.google.com/file/d/1gwlUroqTuKVqixRMm5X4_lzfX_9Fu5ga/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 22,
    "caso": "4",
    "casoRaiz": "4",
    "id": "004/2026",
    "semId": false,
    "etapa": "Acórdão - PSS",
    "origem": "DF 2026",
    "clube": "Palmeiras",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Turma de Julgamento 01",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "05/06/2026",
    "dataEntrega": "",
    "observacao": "Turma 01 - Decidido advertência por não publicação das DFs",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1ag68SFmtMNTD7A40YrHHL8uN7lTDAa1b/view?usp=drive_link",
    "turma": "Turma 01",
    "dataDecisao": "29/05/2026",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 23,
    "caso": "4",
    "casoRaiz": "4",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "Palmeiras",
    "serie": "A",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "5 dias úties para reconsideração",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "12/06/2026",
    "dataEntrega": "",
    "observacao": "Não houve pedido de reconsideração",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 24,
    "caso": "5",
    "casoRaiz": "5",
    "id": "005/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "DF 2026",
    "clube": "Vasco",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do dever de publicação das DFs",
    "dataEnvio": "15/05/2026",
    "prazoFinal": "20/05/2026",
    "dataEntrega": "20/05/2026",
    "observacao": "O Clube apresentou defesa e DF publicada",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência + Multa 40k",
    "doc": "https://drive.google.com/file/d/1h5X24O0m4Gg-dNX1IaSy5PpnBzHH4w0c/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 25,
    "caso": "5",
    "casoRaiz": "5",
    "id": "005/2026",
    "semId": false,
    "etapa": "Acórdão - PSS",
    "origem": "DF 2026",
    "clube": "Vasco",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Turma de Julgamento 01",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "05/06/2026",
    "dataEntrega": "",
    "observacao": "Turma 01 - Decidido advertência por não publicação das DFs",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1ztyGABcMfZUK7nNieXQjiyg6rGtMyYQM/view?usp=drive_link",
    "turma": "Turma 01",
    "dataDecisao": "29/05/2026",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 26,
    "caso": "5",
    "casoRaiz": "5",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "Vasco",
    "serie": "A",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "5 dias úties para reconsideração",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "12/06/2026",
    "dataEntrega": "",
    "observacao": "Não houve pedido de reconsideração",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 27,
    "caso": "6",
    "casoRaiz": "6",
    "id": "006/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "DF 2026",
    "clube": "Cuiabá",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do dever de publicação das DFs",
    "dataEnvio": "15/05/2026",
    "prazoFinal": "20/05/2026",
    "dataEntrega": "15/05/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Multa 20k",
    "doc": "https://drive.google.com/file/d/1L5D8BT9aP9rlOurVh1-HAYlGyr9Y-c43/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 28,
    "caso": "6",
    "casoRaiz": "6",
    "id": "006/2026",
    "semId": false,
    "etapa": "Acórdão - PSS",
    "origem": "DF 2026",
    "clube": "Cuiabá",
    "serie": "B",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Turma de Julgamento 01",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "05/06/2026",
    "dataEntrega": "",
    "observacao": "Turma 01 - Decidido advertência por não publicação das DFs + Prazo para publicação",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1BVvJ3TW-2CxDVQ3WeoQIUBSmdQkZNn1Y/view?usp=drive_link",
    "turma": "Turma 01",
    "dataDecisao": "29/05/2026",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 29,
    "caso": "6",
    "casoRaiz": "6",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "Cuiabá",
    "serie": "B",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "5 dias úties para reconsideração",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "12/06/2026",
    "dataEntrega": "",
    "observacao": "Não houve pedido de reconsideração",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 30,
    "caso": "6.1",
    "casoRaiz": "6",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "Cuiabá",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Acompanhar publicação das DFs",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "07/07/2026",
    "dataEntrega": "",
    "observacao": "Acompanhar publicação das DFs",
    "statusEtapa": "Pendente Clube",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 31,
    "caso": "7",
    "casoRaiz": "7",
    "id": "007/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "DF 2026",
    "clube": "Remo",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do dever de publicação das DFs",
    "dataEnvio": "15/05/2026",
    "prazoFinal": "20/05/2026",
    "dataEntrega": "20/05/2026",
    "observacao": "O Clube apresentou defesa e DF publicada",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência + Multa 40k",
    "doc": "https://drive.google.com/file/d/10it0RYyQettYRcDD_UySZg6K5pQUmDio/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 32,
    "caso": "7",
    "casoRaiz": "7",
    "id": "007/2026",
    "semId": false,
    "etapa": "Acórdão - PSS",
    "origem": "DF 2026",
    "clube": "Remo",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Turma de Julgamento 01",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "05/06/2026",
    "dataEntrega": "",
    "observacao": "Turma 01 - Decidido advertência por não publicação das DFs",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1p8rfOWz3AyWvXAxAFJ-vUUqsW3Av3CP6/view?usp=drive_link",
    "turma": "Turma 01",
    "dataDecisao": "29/05/2026",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 33,
    "caso": "7",
    "casoRaiz": "7",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "Remo",
    "serie": "A",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "5 dias úties para reconsideração",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "12/06/2026",
    "dataEntrega": "",
    "observacao": "Não houve pedido de reconsideração",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 34,
    "caso": "8",
    "casoRaiz": "8",
    "id": "008/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "DF 2026",
    "clube": "São Bernardo",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do dever de publicação das DFs",
    "dataEnvio": "15/05/2026",
    "prazoFinal": "20/05/2026",
    "dataEntrega": "20/05/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência + Multa 20k",
    "doc": "https://drive.google.com/file/d/1S5SgSEiLoDAUuLEQ1P2cqe-VD-ygqXjZ/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 35,
    "caso": "8",
    "casoRaiz": "8",
    "id": "008/2026",
    "semId": false,
    "etapa": "Acórdão - PSS",
    "origem": "DF 2026",
    "clube": "São Bernardo",
    "serie": "B",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Turma de Julgamento 01",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "05/06/2026",
    "dataEntrega": "",
    "observacao": "Turma 01 - Decidido advertência por não publicação das DFs + Prazo para publicação",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1rpQzQog725SLW8-Imyb0ol4WwnzQjv4w/view?usp=drive_link",
    "turma": "Turma 01",
    "dataDecisao": "29/05/2026",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 36,
    "caso": "8",
    "casoRaiz": "8",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "São Bernardo",
    "serie": "B",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "5 dias úties para reconsideração",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "12/06/2026",
    "dataEntrega": "",
    "observacao": "Não houve pedido de reconsideração",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 37,
    "caso": "8.1",
    "casoRaiz": "8",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "São Bernardo",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Acompanhar publicação das DFs",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "17/07/2026",
    "dataEntrega": "",
    "observacao": "Clube comprovou a publicação das DFs",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 38,
    "caso": "9",
    "casoRaiz": "9",
    "id": "009/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "DF 2026",
    "clube": "Londrina",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do dever de publicação das DFs",
    "dataEnvio": "15/05/2026",
    "prazoFinal": "20/05/2026",
    "dataEntrega": "20/05/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Multa 20k",
    "doc": "https://drive.google.com/file/d/1h9MAxxPaSr0zzqNTHI-bIwrkZvTNTjZr/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 39,
    "caso": "9",
    "casoRaiz": "9",
    "id": "009/2026",
    "semId": false,
    "etapa": "Acórdão - PSS",
    "origem": "DF 2026",
    "clube": "Londrina",
    "serie": "B",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Turma de Julgamento 01",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "05/06/2026",
    "dataEntrega": "",
    "observacao": "Turma 01 - Decidido advertência por não publicação das DFs + Prazo para publicação",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1o83zcLGjMdiOfLZePzLYUkjIgEBX2wng/view?usp=drive_link",
    "turma": "Turma 01",
    "dataDecisao": "29/05/2026",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 40,
    "caso": "9",
    "casoRaiz": "9",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "Londrina",
    "serie": "B",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "5 dias úties para reconsideração",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "12/06/2026",
    "dataEntrega": "12/06/2026",
    "observacao": "Pedido de reconsideração por parte do Clube",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 41,
    "caso": "9",
    "casoRaiz": "9",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "Londrina",
    "serie": "B",
    "ordem": 4,
    "ordemLabel": "4",
    "objeto": "Avaliaçao do Pedido de reconsideração do Acórdão 009/2026",
    "dataEnvio": "12/06/2026",
    "prazoFinal": "19/06/2026",
    "dataEntrega": "07/07/2026",
    "observacao": "",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 42,
    "caso": "9.1",
    "casoRaiz": "9",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "Londrina",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Acompanhar publicação das DFs",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "17/07/2026",
    "dataEntrega": "",
    "observacao": "Acompanhar publicação das DFs",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 43,
    "caso": "9.1",
    "casoRaiz": "9",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "Londrina",
    "serie": "B",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "DF Publicada",
    "dataEnvio": "12/06/2026",
    "prazoFinal": "12/06/2026",
    "dataEntrega": "12/06/2026",
    "observacao": "DF Publicada",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 44,
    "caso": "10",
    "casoRaiz": "10",
    "id": "010/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "DF 2026",
    "clube": "Avaí",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do dever de publicação das DFs",
    "dataEnvio": "15/05/2026",
    "prazoFinal": "20/05/2026",
    "dataEntrega": "20/05/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Multa 20k",
    "doc": "https://drive.google.com/file/d/1_OJgVKyQKreQnHo-BNKwlv_ISUq0Y1Ib/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 45,
    "caso": "10",
    "casoRaiz": "10",
    "id": "010/2026",
    "semId": false,
    "etapa": "Acórdão - PSS",
    "origem": "DF 2026",
    "clube": "Avaí",
    "serie": "B",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Turma de Julgamento 01",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "05/06/2026",
    "dataEntrega": "",
    "observacao": "Turma 01 - Decidido advertência por não publicação das DFs + Prazo para publicação",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1RTLKbsYIlwPvMXTbunjdagy5BLMX4KEr/view",
    "turma": "Turma 01",
    "dataDecisao": "29/05/2026",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 46,
    "caso": "10",
    "casoRaiz": "10",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "Avaí",
    "serie": "B",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "5 dias úties para reconsideração",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "12/06/2026",
    "dataEntrega": "",
    "observacao": "Acompanhar possível reconsideração",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 47,
    "caso": "10.1",
    "casoRaiz": "10",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "Avaí",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Acompanhar publicação das DFs",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "07/07/2026",
    "dataEntrega": "",
    "observacao": "Acompanhar publicação das DFs",
    "statusEtapa": "Pendente Clube",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 48,
    "caso": "11",
    "casoRaiz": "11",
    "id": "011/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "DF 2026",
    "clube": "CRB",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do dever de publicação das DFs",
    "dataEnvio": "15/05/2026",
    "prazoFinal": "20/05/2026",
    "dataEntrega": "20/05/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Multa 20k",
    "doc": "https://drive.google.com/file/d/1PkPche3PknPug-43j1zk86SBQe1mtXv3/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 49,
    "caso": "11",
    "casoRaiz": "11",
    "id": "011/2026",
    "semId": false,
    "etapa": "Acórdão - PSS",
    "origem": "DF 2026",
    "clube": "CRB",
    "serie": "B",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Turma de Julgamento 01",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "05/06/2026",
    "dataEntrega": "",
    "observacao": "Turma 01 - Decidido advertência por não publicação das DFs + Prazo para publicação",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1jTRRT9_GVQM4URWWHBeMQTVNAq-NvZ48/view",
    "turma": "Turma 01",
    "dataDecisao": "29/05/2026",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 50,
    "caso": "11",
    "casoRaiz": "11",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "CRB",
    "serie": "B",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "5 dias úties para reconsideração",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "12/06/2026",
    "dataEntrega": "",
    "observacao": "Não houve pedido de reconsideração",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 51,
    "caso": "11.1",
    "casoRaiz": "11",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "CRB",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Acompanhar publicação das DFs",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "06/09/2026",
    "dataEntrega": "",
    "observacao": "Acompanhar publicação das DFs",
    "statusEtapa": "Pendente Clube",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 52,
    "caso": "12",
    "casoRaiz": "12",
    "id": "012/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "DF 2026",
    "clube": "Ponte Preta",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do dever de publicação das DFs",
    "dataEnvio": "15/05/2026",
    "prazoFinal": "20/05/2026",
    "dataEntrega": "20/05/2026",
    "observacao": "O Clube apresentou defesa e DF publicada",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência + Multa 20k",
    "doc": "https://drive.google.com/file/d/1il7jU-dtlIFuyP4XIivyysFePVNYGJSf/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 53,
    "caso": "12",
    "casoRaiz": "12",
    "id": "012/2026",
    "semId": false,
    "etapa": "Acórdão - PSS",
    "origem": "DF 2026",
    "clube": "Ponte Preta",
    "serie": "B",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Turma de Julgamento 01",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "05/06/2026",
    "dataEntrega": "",
    "observacao": "Turma 01 - Decidido advertência por não publicação das DFs",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1UAE2HwLZHc0q4xdDLo8Y1USVyHwUcS_n/view",
    "turma": "Turma 01",
    "dataDecisao": "29/05/2026",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 54,
    "caso": "12",
    "casoRaiz": "12",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "Ponte Preta",
    "serie": "B",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "5 dias úties para reconsideração",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "12/06/2026",
    "dataEntrega": "",
    "observacao": "Não houve pedido de reconsideração",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 55,
    "caso": "13",
    "casoRaiz": "13",
    "id": "013/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "DF 2026",
    "clube": "SAF Botafogo",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do dever de publicação das DFs",
    "dataEnvio": "15/05/2026",
    "prazoFinal": "20/05/2026",
    "dataEntrega": "20/05/2026",
    "observacao": "O Clube apresentou defesa e DF publicada",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1ky3eFDuP3sq7702rGZU7ZZFGaMnYP1yc/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 56,
    "caso": "13",
    "casoRaiz": "13",
    "id": "013/2026",
    "semId": false,
    "etapa": "Acórdão - PSS",
    "origem": "DF 2026",
    "clube": "SAF Botafogo",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Turma de Julgamento 01",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "05/06/2026",
    "dataEntrega": "",
    "observacao": "Turma 01 - Decidido advertência por não publicação das DFs",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1ZX3ACExsIa6XlnctSNq_3nnKCwI8Fc-g/view?usp=drive_link",
    "turma": "Turma 01",
    "dataDecisao": "29/05/2026",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 57,
    "caso": "13",
    "casoRaiz": "13",
    "id": "",
    "semId": true,
    "etapa": "Acompanhamento",
    "origem": "DF 2026",
    "clube": "SAF Botafogo",
    "serie": "A",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "5 dias úties para reconsideração",
    "dataEnvio": "05/06/2026",
    "prazoFinal": "12/06/2026",
    "dataEntrega": "",
    "observacao": "Não houve pedido de reconsideração",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 58,
    "caso": "14",
    "casoRaiz": "14",
    "id": "015/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "Solvência 2026/02/28",
    "clube": "SAF Botafogo",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Não reporte do Requisito de Solvência",
    "dataEnvio": "15/05/2026",
    "prazoFinal": "20/05/2026",
    "dataEntrega": "20/05/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência + Multa 100k + 20k por dia",
    "doc": "https://drive.google.com/file/d/1e-2viFBNZeXXvGO0WfHJRW3C13EWZ8zG/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 59,
    "caso": "14",
    "casoRaiz": "14",
    "id": "015/2026",
    "semId": false,
    "etapa": "Acórdão - PSS",
    "origem": "Solvência 2026/02/28",
    "clube": "SAF Botafogo",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Turma de Julgamento 02",
    "dataEnvio": "03/06/2026",
    "prazoFinal": "03/06/2026",
    "dataEntrega": "",
    "observacao": "Turma 02 - Decidido advertência por não reporte da Solvência",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1pfinNHR9-yi72YQZGOqqeI3GFZlPAzYO/view?usp=drive_link",
    "turma": "Turma 02",
    "dataDecisao": "29/05/2026",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 60,
    "caso": "15",
    "casoRaiz": "15",
    "id": "016/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "Solvência 2026/02/28",
    "clube": "São Bernardo",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Não reporte do Requisito de Solvência",
    "dataEnvio": "15/05/2026",
    "prazoFinal": "20/05/2026",
    "dataEntrega": "20/05/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência + Multa 50k + 10k por dia",
    "doc": "https://drive.google.com/file/d/1EOUO2F50KvP7noGD5kgZcOsOQqKcCu5S/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 61,
    "caso": "15",
    "casoRaiz": "15",
    "id": "016/2026",
    "semId": false,
    "etapa": "Acórdão - PSS",
    "origem": "Solvência 2026/02/28",
    "clube": "São Bernardo",
    "serie": "B",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Turma de Julgamento 02",
    "dataEnvio": "03/06/2026",
    "prazoFinal": "03/06/2026",
    "dataEntrega": "",
    "observacao": "Turma 02 - Decidido advertência por não reporte da Solvência",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1CgqxgUsqgSG9Nv5MDOWAyEKaEsLFr0zh/view?usp=drive_link",
    "turma": "Turma 02",
    "dataDecisao": "29/05/2026",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 62,
    "caso": "16",
    "casoRaiz": "16",
    "id": "003/2026",
    "semId": false,
    "etapa": "Diligência",
    "origem": "Monitoramento 2026",
    "clube": "Avaí",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Acompanhar envio de documentos",
    "dataEnvio": "28/05/2026",
    "prazoFinal": "26/05/2026",
    "dataEntrega": "",
    "observacao": "O Clube não enviou os documentos e foi aberto um auto de infração",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "https://drive.google.com/file/d/1ifZTag50iUB3oLOX0LshnUzNUDuMclWr/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 63,
    "caso": "16.1",
    "casoRaiz": "16",
    "id": "014/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "Monitoramento 2026",
    "clube": "Avaí",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Pelo não envio de documentação",
    "dataEnvio": "03/06/2026",
    "prazoFinal": "09/06/2026",
    "dataEntrega": "09/06/2026",
    "observacao": "Defesa apresentada e documentos entregues",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Multa 50k + 10k por dia",
    "doc": "https://drive.google.com/file/d/1DDCxCC9HQMv2UqVdxUZAP2qfCggDlIt9/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 64,
    "caso": "16.1",
    "casoRaiz": "16",
    "id": "014/2026",
    "semId": false,
    "etapa": "Acórdão - PSS",
    "origem": "Monitoramento 2026",
    "clube": "Avaí",
    "serie": "B",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Turma de Julgamento 02",
    "dataEnvio": "09/06/2026",
    "prazoFinal": "08/07/2026",
    "dataEntrega": "",
    "observacao": "Aguardando decisão",
    "statusEtapa": "Pendente ANRESF",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "Turma 02",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 65,
    "caso": "17",
    "casoRaiz": "17",
    "id": "018/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "Solvência 2026/02/28",
    "clube": "Athletico PR",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026)",
    "dataEnvio": "02/06/2026",
    "prazoFinal": "08/06/2026",
    "dataEntrega": "05/06/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1rs7v6sluFRCT5CUYRDCgtyR9l_gwJCDq/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 66,
    "caso": "17",
    "casoRaiz": "17",
    "id": "001/2026",
    "semId": false,
    "etapa": "Acórdão Decisão da Presidência - PSS",
    "origem": "Solvência 2026/02/28",
    "clube": "Athletico PR",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Presidência",
    "dataEnvio": "08/06/2026",
    "prazoFinal": "08/07/2026",
    "dataEntrega": "",
    "observacao": "Presidência - Decidido assegurar prazo de defesa de 10 dias úteis",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Sem sanção",
    "doc": "",
    "turma": "Presidência",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 67,
    "caso": "18",
    "casoRaiz": "18",
    "id": "019/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Atlético MG",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: Tributárias)",
    "dataEnvio": "02/06/2026",
    "prazoFinal": "17/06/2026",
    "dataEntrega": "",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Não regularização acarretará nova Infração",
    "doc": "https://drive.google.com/file/d/1pKoWaFJgra92vmCv2zAcincFcMU3n34E/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 68,
    "caso": "18",
    "casoRaiz": "18",
    "id": "005/2026",
    "semId": false,
    "etapa": "Parecer Técnico Conclusivo",
    "origem": "Solvência 2026/02/28",
    "clube": "Atlético MG",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Para distribuição das Turmas de Julgamento",
    "dataEnvio": "17/06/2026",
    "prazoFinal": "02/07/2026",
    "dataEntrega": "02/07/2026",
    "observacao": "Documentação enviada para avaliação da Turma 02",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "https://drive.google.com/file/d/19UH--HntcN6m21Pw1GFWmu7GkJXkczsC/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 69,
    "caso": "18",
    "casoRaiz": "18",
    "id": "019/2026",
    "semId": false,
    "etapa": "Acórdão - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Atlético MG",
    "serie": "A",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "Avaliação pela Turma de Julgamento 02",
    "dataEnvio": "02/07/2026",
    "prazoFinal": "08/07/2026",
    "dataEntrega": "",
    "observacao": "Aguardando decisão",
    "statusEtapa": "Pendente ANRESF",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "Turma 02",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 70,
    "caso": "19",
    "casoRaiz": "19",
    "id": "020/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "SAF Botafogo",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: (i) Pessoas Relevantes + (ii) Tributárias )",
    "dataEnvio": "02/06/2026",
    "prazoFinal": "17/06/2026",
    "dataEntrega": "17/06/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + (i) Multa 100k + (ii) Não regularização acarretará nova Infração",
    "doc": "https://drive.google.com/file/d/1khPANQTefKYh1jlgJsH8SKZSYkavcWlU/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 71,
    "caso": "19",
    "casoRaiz": "19",
    "id": "006/2026",
    "semId": false,
    "etapa": "Parecer Técnico Conclusivo",
    "origem": "Solvência 2026/02/28",
    "clube": "SAF Botafogo",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Para distribuição das Turmas de Julgamento",
    "dataEnvio": "17/06/2026",
    "prazoFinal": "02/07/2026",
    "dataEntrega": "02/07/2026",
    "observacao": "Documentação enviada para avaliação da Turma 02",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "https://drive.google.com/file/d/1xZa3KA-L12eU2mYnU9IH9QNlMx67p6Ug/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 72,
    "caso": "19",
    "casoRaiz": "19",
    "id": "020/2026",
    "semId": false,
    "etapa": "Acórdão - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "SAF Botafogo",
    "serie": "A",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "Avaliação pela Turma de Julgamento 02",
    "dataEnvio": "02/07/2026",
    "prazoFinal": "08/07/2026",
    "dataEntrega": "",
    "observacao": "Aguardando decisão",
    "statusEtapa": "Pendente ANRESF",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "Turma 02",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 73,
    "caso": "20",
    "casoRaiz": "20",
    "id": "021/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Corinthians",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: Tributárias)",
    "dataEnvio": "02/06/2026",
    "prazoFinal": "17/06/2026",
    "dataEntrega": "17/06/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Não regularização acarretará nova Infração",
    "doc": "https://drive.google.com/file/d/1gIac9xrsw8u5Z1dGC3oDU9ysmN9kDnqn/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 74,
    "caso": "20",
    "casoRaiz": "20",
    "id": "007/2026",
    "semId": false,
    "etapa": "Parecer Técnico Conclusivo",
    "origem": "Solvência 2026/02/28",
    "clube": "Corinthians",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Para distribuição das Turmas de Julgamento",
    "dataEnvio": "17/06/2026",
    "prazoFinal": "02/07/2026",
    "dataEntrega": "02/07/2026",
    "observacao": "Documentação enviada para avaliação da Turma 02",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "https://drive.google.com/file/d/1xXW2_iMSm4a84609AtS2S8ty-y-KzGQ4/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 75,
    "caso": "20",
    "casoRaiz": "20",
    "id": "021/2026",
    "semId": false,
    "etapa": "Acórdão - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Corinthians",
    "serie": "A",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "Avaliação pela Turma de Julgamento 02",
    "dataEnvio": "02/07/2026",
    "prazoFinal": "08/07/2026",
    "dataEntrega": "",
    "observacao": "Aguardando decisão",
    "statusEtapa": "Pendente ANRESF",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "Turma 02",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 76,
    "caso": "21",
    "casoRaiz": "21",
    "id": "022/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Fluminense",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: Tributárias)",
    "dataEnvio": "02/06/2026",
    "prazoFinal": "17/06/2026",
    "dataEntrega": "16/06/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Não regularização acarretará nova Infração",
    "doc": "https://drive.google.com/file/d/1VriZ5mQGaLQZka4EDQBRDNIEVsBObRuN/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 77,
    "caso": "21",
    "casoRaiz": "21",
    "id": "008/2026",
    "semId": false,
    "etapa": "Parecer Técnico Conclusivo",
    "origem": "Solvência 2026/02/28",
    "clube": "Fluminense",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Para distribuição das Turmas de Julgamento",
    "dataEnvio": "17/06/2026",
    "prazoFinal": "02/07/2026",
    "dataEntrega": "02/07/2026",
    "observacao": "Documentação enviada para avaliação da Turma 02",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "https://drive.google.com/file/d/1RZTOIupWFTM5wfk-CIT_1ZxRh25wIBK8/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 78,
    "caso": "21",
    "casoRaiz": "21",
    "id": "022/2026",
    "semId": false,
    "etapa": "Acórdão - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Fluminense",
    "serie": "A",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "Avaliação pela Turma de Julgamento 02",
    "dataEnvio": "02/07/2026",
    "prazoFinal": "08/07/2026",
    "dataEntrega": "",
    "observacao": "Aguardando decisão",
    "statusEtapa": "Pendente ANRESF",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "Turma 02",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 79,
    "caso": "22",
    "casoRaiz": "22",
    "id": "023/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Gremio",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: Tributárias)",
    "dataEnvio": "02/06/2026",
    "prazoFinal": "17/06/2026",
    "dataEntrega": "12/06/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Não regularização acarretará nova Infração",
    "doc": "https://drive.google.com/file/d/1alwgip7HeDwtX_2eLuAkkIYcpjTeqxOa/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 80,
    "caso": "22",
    "casoRaiz": "22",
    "id": "009/2026",
    "semId": false,
    "etapa": "Parecer Técnico Conclusivo",
    "origem": "Solvência 2026/02/28",
    "clube": "Gremio",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Para distribuição das Turmas de Julgamento",
    "dataEnvio": "17/06/2026",
    "prazoFinal": "02/07/2026",
    "dataEntrega": "02/07/2026",
    "observacao": "Documentação enviada para avaliação da Turma 02",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "https://drive.google.com/file/d/1ovmrlxNijgJoEnnxixQSzh08vdqir1pb/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 81,
    "caso": "22",
    "casoRaiz": "22",
    "id": "023/2026",
    "semId": false,
    "etapa": "Acórdão - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Gremio",
    "serie": "A",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "Avaliação pela Turma de Julgamento 02",
    "dataEnvio": "02/07/2026",
    "prazoFinal": "08/07/2026",
    "dataEntrega": "",
    "observacao": "Aguardando decisão",
    "statusEtapa": "Pendente ANRESF",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "Turma 02",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 82,
    "caso": "23",
    "casoRaiz": "23",
    "id": "024/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "Solvência 2026/02/28",
    "clube": "Internacional",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026)",
    "dataEnvio": "02/06/2026",
    "prazoFinal": "08/06/2026",
    "dataEntrega": "08/06/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/16GshBOnUngVfR7KvVCzi3-BA5lf38lt3/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 83,
    "caso": "23",
    "casoRaiz": "23",
    "id": "002/2026",
    "semId": false,
    "etapa": "Acórdão Decisão da Presidência - PSS",
    "origem": "Solvência 2026/02/28",
    "clube": "Internacional",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Presidência",
    "dataEnvio": "08/06/2026",
    "prazoFinal": "08/07/2026",
    "dataEntrega": "",
    "observacao": "Presidência - Decidido assegurar prazo de defesa de 10 dias úteis",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Sem sanção",
    "doc": "",
    "turma": "Presidência",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 84,
    "caso": "24",
    "casoRaiz": "24",
    "id": "025/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "Solvência 2026/02/28",
    "clube": "Palmeiras",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026)",
    "dataEnvio": "02/06/2026",
    "prazoFinal": "08/06/2026",
    "dataEntrega": "08/06/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1_VNAEzWYOgje4ECCPcG1BWnoizG4uXzI/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 85,
    "caso": "24",
    "casoRaiz": "24",
    "id": "003/2026",
    "semId": false,
    "etapa": "Acórdão Decisão da Presidência - PSS",
    "origem": "Solvência 2026/02/28",
    "clube": "Palmeiras",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Presidência",
    "dataEnvio": "08/06/2026",
    "prazoFinal": "08/07/2026",
    "dataEntrega": "",
    "observacao": "Presidência - Decidido assegurar prazo de defesa de 10 dias úteis",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Sem sanção",
    "doc": "",
    "turma": "Presidência",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 86,
    "caso": "25",
    "casoRaiz": "25",
    "id": "026/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Remo",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: Tributárias)",
    "dataEnvio": "02/06/2026",
    "prazoFinal": "17/06/2026",
    "dataEntrega": "16/06/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Não regularização acarretará nova Infração",
    "doc": "https://drive.google.com/file/d/1dq-ek10BUhUQWTNIXGZwl3C1_JULTFIN/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 87,
    "caso": "25",
    "casoRaiz": "25",
    "id": "010/2026",
    "semId": false,
    "etapa": "Parecer Técnico Conclusivo",
    "origem": "Solvência 2026/02/28",
    "clube": "Remo",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Para distribuição das Turmas de Julgamento",
    "dataEnvio": "17/06/2026",
    "prazoFinal": "02/07/2026",
    "dataEntrega": "02/07/2026",
    "observacao": "Documentação enviada para avaliação da Turma 02",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "https://drive.google.com/file/d/1FtNJr8a5Y7HG9GXe6kNwAUUQvj9Ma-Wo/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 88,
    "caso": "25",
    "casoRaiz": "25",
    "id": "024/2026",
    "semId": false,
    "etapa": "Acórdão - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Remo",
    "serie": "A",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "Avaliação pela Turma de Julgamento 02",
    "dataEnvio": "02/07/2026",
    "prazoFinal": "08/07/2026",
    "dataEntrega": "",
    "observacao": "Aguardando decisão",
    "statusEtapa": "Pendente ANRESF",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "Turma 02",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 89,
    "caso": "26",
    "casoRaiz": "26",
    "id": "027/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSS",
    "origem": "Solvência 2026/02/28",
    "clube": "Santos",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026)",
    "dataEnvio": "02/06/2026",
    "prazoFinal": "08/06/2026",
    "dataEntrega": "08/06/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1c6qRP6YDXSsQqwGDF_tXi6VOAq1x4S8w/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 90,
    "caso": "26",
    "casoRaiz": "26",
    "id": "004/2026",
    "semId": false,
    "etapa": "Acórdão Decisão da Presidência - PSS",
    "origem": "Solvência 2026/02/28",
    "clube": "Santos",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Avaliação pela Presidência",
    "dataEnvio": "08/06/2026",
    "prazoFinal": "08/07/2026",
    "dataEntrega": "",
    "observacao": "Presidência - Decidido assegurar prazo de defesa de 10 dias úteis",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Sem sanção",
    "doc": "",
    "turma": "Presidência",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 91,
    "caso": "27",
    "casoRaiz": "27",
    "id": "028/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "São Paulo",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: (i) Clubes + (ii) Pessoas Relevantes)",
    "dataEnvio": "02/06/2026",
    "prazoFinal": "17/06/2026",
    "dataEntrega": "08/06/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + (i) Multa 100k + (ii) Multa 100k",
    "doc": "https://drive.google.com/file/d/10QoV4cwYAMLMomVliFAPZc6TnsFmGn9j/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 92,
    "caso": "27",
    "casoRaiz": "27",
    "id": "011/2026",
    "semId": false,
    "etapa": "Parecer Técnico Conclusivo",
    "origem": "Solvência 2026/02/28",
    "clube": "São Paulo",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Para distribuição das Turmas de Julgamento",
    "dataEnvio": "17/06/2026",
    "prazoFinal": "02/07/2026",
    "dataEntrega": "02/07/2026",
    "observacao": "Documentação enviada para avaliação da Turma 02",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "https://drive.google.com/file/d/1mcd1x_e-ABdyDIc1Sod5zyeLe1NvydjI/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 93,
    "caso": "27",
    "casoRaiz": "27",
    "id": "025/2026",
    "semId": false,
    "etapa": "Acórdão - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "São Paulo",
    "serie": "A",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "Avaliação pela Turma de Julgamento 02",
    "dataEnvio": "02/07/2026",
    "prazoFinal": "08/07/2026",
    "dataEntrega": "",
    "observacao": "Aguardando decisão",
    "statusEtapa": "Pendente ANRESF",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "Turma 02",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 94,
    "caso": "28",
    "casoRaiz": "28",
    "id": "029/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Vitória",
    "serie": "A",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: Tributárias)",
    "dataEnvio": "02/06/2026",
    "prazoFinal": "17/06/2026",
    "dataEntrega": "17/06/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Não regularização acarretará nova Infração",
    "doc": "https://drive.google.com/file/d/1MpCcwI1FL_lxJielUzXYy4Hsp_N9iarf/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 95,
    "caso": "28",
    "casoRaiz": "28",
    "id": "012/2026",
    "semId": false,
    "etapa": "Parecer Técnico Conclusivo",
    "origem": "Solvência 2026/02/28",
    "clube": "Vitória",
    "serie": "A",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Para distribuição das Turmas de Julgamento",
    "dataEnvio": "17/06/2026",
    "prazoFinal": "02/07/2026",
    "dataEntrega": "02/07/2026",
    "observacao": "Documentação enviada para avaliação da Turma 02",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "https://drive.google.com/file/d/1TBczJfhuWapusYjk36SwO2Ce9u76CEFP/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 96,
    "caso": "28",
    "casoRaiz": "28",
    "id": "026/2026",
    "semId": false,
    "etapa": "Acórdão - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Vitória",
    "serie": "A",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "Avaliação pela Turma de Julgamento 02",
    "dataEnvio": "02/07/2026",
    "prazoFinal": "08/07/2026",
    "dataEntrega": "",
    "observacao": "Aguardando decisão",
    "statusEtapa": "Pendente ANRESF",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "Turma 02",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 97,
    "caso": "29",
    "casoRaiz": "29",
    "id": "030/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "América MG",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: (i) Pessoas Relevantes + (ii) Empregados + (iii) Tributárias)",
    "dataEnvio": "22/06/2026",
    "prazoFinal": "06/07/2026",
    "dataEntrega": "06/07/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + (i) Exclusão PARF-B + (ii) Exclusão PARF-B + (iii) Não regularização acarretará nova Infração",
    "doc": "https://drive.google.com/file/d/1pmsA2FTN96qQ9zHXqljP_eTjMFS8cQHh/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 98,
    "caso": "30",
    "casoRaiz": "30",
    "id": "031/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Atlético GO",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: Tributárias)",
    "dataEnvio": "22/06/2026",
    "prazoFinal": "06/07/2026",
    "dataEntrega": "",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Não regularização acarretará nova Infração",
    "doc": "https://drive.google.com/file/d/1JYLRsyhm5zyTiZa0Gz2vLfdpv85jFQL1/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 99,
    "caso": "31",
    "casoRaiz": "31",
    "id": "032/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Ceará",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: (i) Pessoas Relevantes + (ii) Outros Clubes+ (iii) Tributárias)",
    "dataEnvio": "22/06/2026",
    "prazoFinal": "06/07/2026",
    "dataEntrega": "06/07/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + (i) Exclusão PARF-B + (ii) Exclusão PARF-B + (iii) Não regularização acarretará nova Infração",
    "doc": "https://drive.google.com/file/d/1kcnBf870qB-Wup85j7JICIujGtSl3LvU/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 100,
    "caso": "32",
    "casoRaiz": "32",
    "id": "033/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Criciúma",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: Tributárias)",
    "dataEnvio": "22/06/2026",
    "prazoFinal": "06/07/2026",
    "dataEntrega": "25/06/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Não regularização acarretará nova Infração",
    "doc": "https://drive.google.com/file/d/1HG7XUXlPI3u9_K6zghTZPAHmqihYPzvx/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 101,
    "caso": "33",
    "casoRaiz": "33",
    "id": "034/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Cuiabá",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026)",
    "dataEnvio": "23/06/2026",
    "prazoFinal": "07/07/2026",
    "dataEntrega": "",
    "observacao": "Não apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1xRfkB41Qh3ibs_lDZ2jH8jyhHR3homts/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 102,
    "caso": "34",
    "casoRaiz": "34",
    "id": "035/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Fortaleza",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: (i) Pessoas Relevantes + (ii) Outros Clubes)",
    "dataEnvio": "22/06/2026",
    "prazoFinal": "06/07/2026",
    "dataEntrega": "06/07/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + (i) Exclusão PARF-B + (ii) Exclusão PARF-B",
    "doc": "https://drive.google.com/file/d/1Q1xTNVvSxNNo_M7meo8MK2Rn0C_mx-eq/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 103,
    "caso": "35",
    "casoRaiz": "35",
    "id": "036/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Londrina",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026)",
    "dataEnvio": "22/06/2026",
    "prazoFinal": "06/07/2026",
    "dataEntrega": "03/07/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/12a45q3yEjfJTDyEilvshYjP95agFJqPg/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 104,
    "caso": "36",
    "casoRaiz": "36",
    "id": "037/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Náutico",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: Tributárias)",
    "dataEnvio": "22/06/2026",
    "prazoFinal": "06/07/2026",
    "dataEntrega": "",
    "observacao": "Não apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Não regularização acarretará nova Infração",
    "doc": "https://drive.google.com/file/d/1q0RDfj7AJ-5d5hK9k2jbBawYPh8fdV5N/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 105,
    "caso": "37",
    "casoRaiz": "37",
    "id": "038/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Sport Recife",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: Tributárias)",
    "dataEnvio": "22/06/2026",
    "prazoFinal": "06/07/2026",
    "dataEntrega": "03/07/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Não regularização acarretará nova Infração",
    "doc": "https://drive.google.com/file/d/12zhjHiZBEKBi-MHMCuVpNE_B86IOQwUx/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 106,
    "caso": "38",
    "casoRaiz": "38",
    "id": "039/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "São Bernardo",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pós 2026: Pessoas Relevantes)",
    "dataEnvio": "22/06/2026",
    "prazoFinal": "06/07/2026",
    "dataEntrega": "",
    "observacao": "Não apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + Exclusão PARF-B",
    "doc": "https://drive.google.com/file/d/1x_CCYvmXgvOEQ3YOBB8ninhW0Kt9Ggj1/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 107,
    "caso": "39",
    "casoRaiz": "39",
    "id": "040/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Vila Nova",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026)",
    "dataEnvio": "23/06/2026",
    "prazoFinal": "07/07/2026",
    "dataEntrega": "26/06/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência",
    "doc": "https://drive.google.com/file/d/1zAln1NHMXq4zdMUFp9zkT2Wzh4dYjFON/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 108,
    "caso": "40",
    "casoRaiz": "40",
    "id": "041/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Ponte Preta",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: (i) Pessoas Relevantes + (ii) Outros Clubes+ (iii) Tributárias + (iv) Empregados)",
    "dataEnvio": "22/06/2026",
    "prazoFinal": "06/07/2026",
    "dataEntrega": "06/07/2026",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + (i) Exclusão PARF-B + (ii) Exclusão PARF-B + (iii) Não regularização acarretará nova Infração + (iv) Exclusão PARF-B",
    "doc": "https://drive.google.com/file/d/1Ndw2alH9UMe25VHmmcQ7mbseEBP36y0Y/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 109,
    "caso": "41",
    "casoRaiz": "41",
    "id": "042/2026",
    "semId": false,
    "etapa": "Auto de Infração - PSO",
    "origem": "Solvência 2026/02/28",
    "clube": "Avaí",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Descumprimento do Requisito de Solvência (Pré 2026 + Pós 2026: (i) Pessoas Relevantes + (ii) Outros Clubes+ (iii) Tributárias)",
    "dataEnvio": "23/06/2026",
    "prazoFinal": "07/07/2026",
    "dataEntrega": "",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "Advertência + (i) Exclusão PARF-B + (ii) Exclusão PARF-B + (iii) Não regularização acarretará nova Infração",
    "doc": "https://drive.google.com/file/d/10wfHuXfmJv2SURZyJIoazbFO-U8n21_g/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 110,
    "caso": "42",
    "casoRaiz": "42",
    "id": "003/2026",
    "semId": false,
    "etapa": "Parecer Técnico Conclusivo",
    "origem": "Denúncia 2026",
    "clube": "Náutico",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Análise da Denúncia enviado pelo Botafogo SP",
    "dataEnvio": "15/05/2026",
    "prazoFinal": "16/06/2026",
    "dataEntrega": "",
    "observacao": "Denúncia admitida - Inadimplemento por parte do Náutico",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 111,
    "caso": "42",
    "casoRaiz": "42",
    "id": "001/2026",
    "semId": false,
    "etapa": "Denúncia",
    "origem": "Denúncia 2026",
    "clube": "Náutico",
    "serie": "B",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Náutico intimado a enviar os comprovantes no prazo de 10 dias úteis",
    "dataEnvio": "16/06/2026",
    "prazoFinal": "30/06/2026",
    "dataEntrega": "19/06/2026",
    "observacao": "Clube apresentou os comprovantes de pagamento",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "",
    "doc": "https://drive.google.com/file/d/1JXXlQ8WHmWsFdS2WqITIIVVLB9NHCQdQ/view?usp=drive_link",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 112,
    "caso": "42",
    "casoRaiz": "42",
    "id": "018/2026",
    "semId": false,
    "etapa": "Acórdão Decisão da Presidência - PSS",
    "origem": "Denúncia 2026",
    "clube": "Náutico",
    "serie": "B",
    "ordem": 3,
    "ordemLabel": "3",
    "objeto": "Avaliação pela Presidência",
    "dataEnvio": "19/06/2026",
    "prazoFinal": "23/06/2026",
    "dataEntrega": "23/06/2026",
    "observacao": "Presidência - Decidido arquivamento do caso, por perda superveniente de objeto",
    "statusEtapa": "Finalizado",
    "statusCaso": "Finalizado",
    "sancao": "Sem sanção",
    "doc": "https://drive.google.com/file/d/1MQWhMj-_rD9ftsSSEyrD1JQN7MUsw0We/view?usp=drive_link",
    "turma": "Presidência",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 113,
    "caso": "43",
    "casoRaiz": "43",
    "id": "004/2026",
    "semId": false,
    "etapa": "Parecer Técnico Conclusivo",
    "origem": "Denúncia 2026",
    "clube": "Sport Recife",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Análise da Denúncia enviado pelo Cuiabá",
    "dataEnvio": "09/06/2026",
    "prazoFinal": "17/06/2026",
    "dataEntrega": "",
    "observacao": "Denúncia admitida - Inadimplemento por parte do Sport Recife",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 114,
    "caso": "43",
    "casoRaiz": "43",
    "id": "002/2026",
    "semId": false,
    "etapa": "Denúncia",
    "origem": "Denúncia 2026",
    "clube": "Sport Recife",
    "serie": "B",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "Sport Recife intimado a enviar os comprovantes no prazo de 10 dias úteis",
    "dataEnvio": "17/06/2026",
    "prazoFinal": "01/07/2026",
    "dataEntrega": "26/06/2026",
    "observacao": "Defesa apresentada e documentos entregues",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 115,
    "caso": "44",
    "casoRaiz": "44",
    "id": "",
    "semId": true,
    "etapa": "Parecer Técnico Conclusivo",
    "origem": "Denúncia 2026",
    "clube": "América MG",
    "serie": "B",
    "ordem": 1,
    "ordemLabel": "1",
    "objeto": "Análise da Denúncia enviado pela Portuguesa RJ",
    "dataEnvio": "19/06/2026",
    "prazoFinal": "24/06/2026",
    "dataEntrega": "",
    "observacao": "Denúncia admitida - Inadimplemento por parte do América MG",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  },
  {
    "row": 116,
    "caso": "44",
    "casoRaiz": "44",
    "id": "003/2026",
    "semId": false,
    "etapa": "Denúncia",
    "origem": "Denúncia 2026",
    "clube": "América MG",
    "serie": "B",
    "ordem": 2,
    "ordemLabel": "2",
    "objeto": "América MG intimado a enviar os comprovantes no prazo de 10 dias úteis",
    "dataEnvio": "24/06/2026",
    "prazoFinal": "08/07/2026",
    "dataEntrega": "",
    "observacao": "O Clube apresentou defesa",
    "statusEtapa": "Finalizado",
    "statusCaso": "Em andamento",
    "sancao": "",
    "doc": "",
    "turma": "",
    "dataDecisao": "",
    "emailResponsavel": "",
    "alertasEnviados": "",
    "ultimoAlertaEnviadoEm": "",
    "idEventoAgenda": "",
    "eventoCriadoEm": ""
  }
];
